---
# tasks file for ansible-role-users

- name: Manage groups
  become: yes
  group:
    gid: "{{ item.gid | default(omit) }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ accounts_groups }}"