---
# tasks file for ansible-role-users

- name: Ensure /etc/sudoers.d exists
  become: yes
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Enable include of /etc/sudoers.d
  become: yes
  lineinfile:
    name: /etc/sudoers
    regexp: "^#includedir"
    line: "#includedir /etc/sudoers.d"
    state: present

- name: Create sudoers configure
  become: yes
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ item.name }}"
  with_items: "{{ users_sudoers }}"

- name: Remove sudoers
  become: yes
  file:
    path: "/etc/sudoers.d/{{ item }}"
    state: absent
  with_items: "{{ users_sudoers_remove }}"

- name: Manage system groups
  become: yes
  group:
    gid: "{{ item.gid | default(omit) }}"
    name: "{{ item.name }}"
    state: "present"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users_groups }}"

- name: Remove groups
  become: yes
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ users_groups_remove }}"

- name: Manage systems users
  become: yes
  user:
    append: "{{ item.append | default(omit) }}"
    comment: "{{ item.gecos | default(item.name) }}"
    createhome: "{{ item.createhome | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default([]) | join(',') | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    login_class: "{{ item.login_class | default(omit) }}"
    move_home: "{{ item.move_home | default(omit) }}"
    name: "{{ item.name }}"
    non_unique: "{{ item.non_unique | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    skeleton: "{{ item.skeleton | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_commnet | default(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ users }}"

- name: Manage authorized_keys
  become: yes
  authorized_key:
    key: "{{ item.1 }}"
    user: "{{ item.0.name }}"
  with_subelements:
    - "{{ users | selectattr('authorized_keys', 'defined') | list }}"
    - authorized_keys

- name: Remove authorized_keys
  become: yes
  authorized_key:
    key: "{{ item.key }}"
    state: absent
    user: "{{ item.user }}"
  with_items: "{{ users_authorized_keys_remove }}"

- name: Remove users
  become: yes
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ users_remove }}"